#!/user/bin/env bash

# which docker-compose & env file to use
COMPOSE_FILE="local"

# docker-compose command
COMPOSE="docker-compose --env-file ./.env.$COMPOSE_FILE -f docker-compose.$COMPOSE_FILE.yml"

if [ $# -gt 0 ]; then

  # If "node" is used, run npm
  # from our node container
  if [ "$1" == "node" ]; then
    shift 1
    $COMPOSE run --rm $TTY \
        node \
        npm "$@"

  # else run command
  else
    $COMPOSE "$@"
  fi
else
  $COMPOSE ps
fi